#SBATCH --output=slurm_output_%A.out

module purge
module load 2022
module load Anaconda3/2022.05

source activate vdm

export CUDA_HOME=$CONDA_PREFIX

cd ~/VAE-VDM/src

srun python -u train.py --results-path results/exp18 --use-encoder --train-num-steps 100000 --eval-every 1000 --num-workers 3 --batch-size 64 --n-blocks 4 --embedding-dim 16 --block-out-channels 16 --layers-per-block 1 --norm-num-groups 8 --w-dim 128