antithetic_time_sampling: true
attention_everywhere: false
batch_size: 64
block_out_channels: 64
clip_grad_norm: true
clip_samples: true
device: cuda
dropout_prob: 0.1
ema_decay: 0.9999
ema_power: 0.75
ema_update_every: 1
embedding_dim: 128
encoder_loss_weight: 10000.0
eval_batch_size: 8
eval_every: 500
gamma_max: 5.0
gamma_min: -13.3
input_channels: 1
layers_per_block: 2
lr: 0.0002
n_attention_heads: 1
n_blocks: 32
noise_schedule: fixed_linear
norm_groups: 32
norm_num_groups: 32
num_sample_steps: 250
num_samples: 64
num_workers: 3
n_samples_for_eval: 1
results_path: null
resume: false
seed: 12345
train_num_steps: 10000
use_encoder: true
use_fourier_features: false
use_mnist: true
w_dim: 128
weight_decay: 0.01
